# Generated by Django 6.0.1 on 2026-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.TextField(blank=True, null=True)),
                ('transmission', models.CharField(default='Automatic', max_length=50)),
                ('seats', models.IntegerField(default=2)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('horsepower', models.IntegerField(default=0)),
                ('zero_to_sixty', models.CharField(blank=True, max_length=50, null=True)),
                ('top_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(default='Available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
