# Generated by Django 6.0.1 on 2026-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gallery',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
