# Generated by Django 6.0.1 on 2026-02-05 06:50

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to=bookings.models.license_upload_path),
        ),
    ]
